apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: imagefactory
  description: Image processing tool
  annotations:
    github.com/project-slug: tomas-u/imageFactory
spec:
  type: tool
  lifecycle: production
  owner: guests
